### ISSUE TITLE
Use tags in opam file

### ISSUE THREAD

**Issue by matsud224** [matsud224/satyrographos-package-index#3]
Tag is useful to classify packages.

*  Show package’s tags at details table
* Show tag list (across all packages)
* Support package search by tag

**Comment by na4zagin3** [comment]
That's a nice idea!  What tags should we start with?

- deprecated
- class
- font
- math
- table
- slide
- bibliography
- markdown

Do we possibly need to add prefix `satysfi:` to some tags like, for example, `satysfi:class`?

**Comment by matsud224** [comment]
I think tag examples mentioned above is good.

> Do we possibly need to add prefix satysfi: to some tags like, for example, satysfi:class?

I think it is redundant because satyrographos-repo is independent from ocaml's repository.

**Comment by matsud224** [comment]
Other opam repository's case:
* In OCaml opam repository, some packages have a tag which has the 'org:' prefix. For example, [aio package](https://opam.ocaml.org/packages/aio/) has 'org:mirage' and 'org:xapi-project' tag.
* In Coq opam repository, some packages have a tag which has the 'category:' or 'keyword:'. See [coq-aac-tactics opam file](https://github.com/coq-community/aac-tactics/blob/master/coq-aac-tactics.opam).

**Comment by matsud224** [comment]
Tag support was added by commit 33bb511d.
